minecraft_version=1.21.1
minecraft_version_range=[1.21.0,1.21.2)

neo_version=21.1.71
neo_version_range=[21.1.62,)
loader_version_range=[4,)

# recommended citresewn version
citresewn_version=1.2.2

mod_id=citresewn_neopatcher
mod_name=CITResewnNeoPatcher
mod_version=1.2.0
mod_authors=HiWord9
mod_description=Patches CITResewn Mod so it runs on NeoForge through Sinytra Connector!
mod_group_id=com.HiWord9

mod_homepage_modrinth = https://modrinth.com/mod/cit-resewn-neopatcher
mod_homepage_curseforge = https://www.curseforge.com/minecraft/mc-mods/cit-resewn-neopatcher

mod_donate_paypal = https://paypal.me/hiword9

mod_sources = https://github.com/HiWord9/CITResewnNeoPatcher
mod_issue_tracker = https://github.com/HiWord9/CITResewnNeoPatcher/issues

mod_license = Team Durt License
mod_license_link = https://license.durt.team
mod_license_version = 1.0

fancy_mod_loader_version=4.0.24